docs(README): Ajout d'une marche à suivre pour maintenir le repo à jour
opt-nc/setup-duckdb-action pull request #116
Opened 2024-08-19 05:36 UTC by ThomDeveo

ref:
- #115

2024-08-19 22:18 UTC, adriens commented
@ThomDeveo , tu ne peux pas t'assigner une PR que tu crées toi-même : peux-tu l'assigner à la bonne personne stp afin qu'elle soit mergées ASAP :pray:

2024-08-21 04:16 UTC, mbarre requested changes
Hello @ThomDeveo ,

J'aurais plutot créer un nouveau fichier HOW_TO_MAINTAINS.md. Pour moi la partie maintenance ne dois pas apparaitre dans la doc qui présente le produit.

Tu trouveras mes remarque dans la review. Si tu as des questions hésite pas.

2024-08-21 04:16 UTC, mbarre commented on README.md
> +`DuckDB` est rarement mis à jour, mais les mises à jour incluent généralement des fonctionnalités importantes.
Ce n'est pas DuckDB que l'on met à jour mais la Github Action setup-duckdb-action.

Mais cette github action va permettre d'installer facilement une version donnée de DuckDB et de basculer facilement vers une nouvelle.

2024-08-21 04:16 UTC, mbarre commented on README.md
> +   - Si la branche n'a pas besoin d'être mise à jour, vous pouvez procéder au merge.
En utilisant `rebase and merge`

2024-08-21 04:16 UTC, mbarre commented on README.md
> +   - Si une mise à jour est nécessaire pour éviter les conflits, recréez la pull request en suivant ces étapes :
Dans le cas, ou une mise à jour et nécessaire et qu'il n'y a pas de conflit, on la **met a jour** la PR

2024-08-21 04:16 UTC, mbarre commented on README.md
> +      - Dependabot ajoutera un "thumbs up" à votre commentaire.
Tu peux remplacer "thumbs up" par :+1:

2024-08-21 04:16 UTC, mbarre commented on README.md
> +      - Attendez que Dependabot réponde en créant une nouvelle pull request.
- Attendez que Dependabot réponde en mettant à jour la pull request.

2024-08-21 04:16 UTC, mbarre commented on README.md
> +
Dans le cas, ou une mise à jour et nécessaire et qu'il a des conflits, on recréer  la PR avec:
`@dependabot recreate`

2024-08-21 04:16 UTC, mbarre commented on README.md
> +   - Parfois, Dependabot ne répond pas après un `rebase`. Si cela se produit, cliquez sur "Create" pour forcer la création de la nouvelle PR.
> Si cela se produit, cliquez sur "Create" pour forcer la création de la nouvelle PR.

Si cela se produit, ajouter le commentaire `@dependabot recreate`

2024-08-22 02:34 UTC, mbarre requested changes

2024-08-22 02:34 UTC, mbarre commented on HOW_TO_MAINTAIN.md
> +
3. Le process de création de release se lance automatiquement. Il est possible de le suivre en allant dans l'onglet Action et cliquer sur le run en cours.
Si le run se termine en erreur, vérifier les logs. En fonction, une simple relance peut rêgler le souci.

2024-08-22 02:34 UTC, mbarre commented on HOW_TO_MAINTAIN.md
> +### ⚙️ GitHub Actions
Je pense que tu peux supprimer cette section.

2024-08-26 04:50 UTC, mbarre approved these changes

2024-08-28 20:06 UTC, mbarre approved these changes

2024-08-28 20:09 UTC, mbarre requested changes

2024-08-28 20:09 UTC, mbarre commented on HOW_TO_MAINTAIN.md
> +      - Si, en discutant avec l'UO qui maintient l'application, la version ne doit pas être montée, ne rien faire.
Tu dois plutot en discuter avec un membre de l'equipe : Adrien ou moi

2024-08-29 00:40 UTC, mbarre approved these changes

2024-08-29 00:40 UTC, merged